version: '3.8'

services:
  mocks:
    image: mocksserver/main
    tty: true
    ports:
      - 3100:3100
      - 3110:3110
    volumes:
      - ./server:/input
    environment:
      - MOCKS_PLUGINS_INQUIRER_CLI_ENABLED=true
